* 数据挖掘之任免工作人员


双节期间，我学习了下数据挖掘。在性能要求不高的场景，Python 在这方面真是简洁
酣畅。“人生苦短，我用 Python。”

本次我对国务院任免工作人员公报进行爬取分析。程序代码在：

https://gitee.com/sd44/showcode/tree/master/src/showcode/renmian


** 成果

数据挖掘的能力往往是很有限的，必须整理极大量信息才能具备统计学价值，但现实中
往往信息资源、开发能力受限。比如本项目数据源仅限于国务院任免工作人员的公报，
来源单一信息量少，且不含党、军职务，不含非公开信息。：


本次数据挖掘 289 个网页，统计出 1999 年 9 月至 2023 年 3 月的 3396 条国务院
工作人员公开任免信息，涉及 1831 位由国务院所管理单位、部门的副部级干部（未统
计主席任命的外交大使）。

任免信息最多的职务统计（前 10 名）：

1. 国有重点大型企业监事会主席	113
2. 外交部副部长	67
3. 国务院副秘书长	55
4. 教育部副部长	48
5. 国家发展和改革委员会副主任	45
6. 中国人民银行副行长	44
7. 工业和信息化部副部长	40
8. 国家税务总局副局长	40
9. 水利部副部长	39
10. 科学技术部副部长	38

通过数据比对连接，仅有 868 条数据完备（单条信息中 人员姓名、职务、任职时
间和免职时间均有效）。单人单职务统计如下：

+ 最低在职时间：38 天
+ 最多在职时间：5775 天（近 16 年）
+ 25%的人在职时长低于：874 天（近两年半）
+ 50%的人在职时长低于：1457 天（近 4 年）
+ 75%的人在职时长低于：2360 天（近 6 年半）
+ 94%的人在职时长低于：10 年

** 项目理由：
1. 信息公开，且国务院网站的 robots.txt 协议里允许爬取公报网页。

2. 文书比较规范，适合分析。通过分析，国务院任免信息主要格式是。
   + 任命 XXX（、XXX） 为 XXXXX（、XXXXX） (2)免去 XXX（、XXX) 的 XXXXX（、
     XXXXX) 职务 （3）任命 XXX 为 XXXXX，免去其 XXXXX（、XXXXXX） 职务。 （4）
     兼任，和不再兼任的表述比较少，只有十几条左右，不影响大局，忽略。

3. 时代的滥觞——流量。选个“看起来”高大上的题目。-__-


** 基本流程
1，通过 playwright 抓取近 300 个公报信息 htm url。
2, 通过 beautifulsoup4 对 url 网页数据进行抓取。
3, 通过 pandas 对抓取信息清洗整理成 excel。

** 主要问题有

1. 针对空值、错误值为省事不做验证，结果常遭现世报。以后应当测试先行。
2. 正则表达式的精准细致运用上还有问题。
3. 性能方面应还可以提高，也欢迎大家积极探讨优化。
